name: Corney
on:
  push:
    branches:
      - sohrab

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: |
        [
          "corne_left nice_view_adapter nice_view",
          "corne_right nice_view_adapter nice_view"
        ]
      clipboard: '["mac"]'
      alphas: '["qwerty"]'
      # i really tried to break this down to multiple lines but no dice :(
      kconfig: '["CONFIG_ZMK_KEYBOARD_NAME=\\\"Corney\\\"\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_WPM=n\nCONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y\nCONFIG_ZMK_WIDGET_WPM_STATUS=n"]'
